### ISSUE TITLE
pg_stat_kcache Section not found in my pg_profile report

### ISSUE THREAD

**Issue by seriousbaguette** [zubkov-andrei/pg_profile#12]
Hello, 
first of all thank you for your awesome work - coming from Oracle this tool is really a life saver ! :-)
I have  a collect server-175 and a source-server-03 where I pull the pg_profile information from. The database is on postgres 12.
After installing pg_stat_kcache on the source-server-03 and restartet the DB I expected to have a pg_profile section similar to your test report but it is not there. 
Do i have to configure something extra ? 

Greetings, 
Andi

**Comment by zubkov-andrei** [comment]
Hello, Andi!

Are you using *pg_stat_kcache* version 2.1.3? Right now *pg_profile* version release 0.1.4 doesn't support it yet. It's just missing. A week ago pull request #11 fixing this issue was merged into master branch of *pg_profile*. But since that there was not releases. Right now, you have to build extension from master branch.

**Comment by zubkov-andrei** [comment]
Release 0.2.1 includes the fix.
