### ISSUE TITLE
Not able to Take snapshots in pg_profile 0.3.3 

### ISSUE THREAD

**Issue by anandkatti** [zubkov-andrei/pg_profile#23]
installed the the pg_profile in public.

**Comment by anandkatti** [comment]
postgres=# SELECT create_server(‘local’,’host=bos1-vcloud-static-172-134.eng.vmware.com dbname=postgres  user=‘perf_mon’ port=5432');
postgres'# select server_connstr('local','dbname=postgres port=5432 user=profile_mon password=pwd_mon');
postgres'# SELECT set_server_size_sampling('local','23:00+03',interval '2 hour',interval '8 hour');
postgres'# SELECT * FROM show_servers_size_sampling();
postgres'# SELECT profile.take_sample()
postgres'# select snapshots()
postgres'# SELECT * FROM show_servers_size_sampling();
postgres'# 

Here are the commands i executed. 

No rows when i quired the DB. 

Could you please help

**Comment by anandkatti** [comment]
<img width="220" alt="Screenshot 2021-08-18 at 9 25 42 AM" src="https://user-images.githubusercontent.com/4032652/129834533-c0ed6c48-1b30-4453-9dd1-831d016d3af1.png">

**Comment by anandkatti** [comment]
there is no pg_profile DB created.

**Comment by anandkatti** [comment]
Here is the outout from each command - 

[root@postgres pg_profile]# sudo make USE_PGXS=y install
/bin/mkdir -p '/usr/pgsql-10/share/extension'
/bin/mkdir -p '/usr/pgsql-10/share/extension'
/bin/install -c -m 644 .//pg_profile.control '/usr/pgsql-10/share/extension/'
/bin/install -c -m 644  pg_profile--0.3.3.sql pg_profile.control pg_profile--0.3.2--0.3.3.sql '/usr/pgsql-10/share/extension/'
[root@postgres pg_profile]# 


[root@postgres pg_profile]# make USE_PGXS=y installcheck
/usr/pgsql-10/lib/pgxs/src/makefiles/../../src/test/regress/pg_regress --inputdir=./ --bindir='/usr/pgsql-10/bin'    --dbname=contrib_regression create_extension server_management samples_and_reports export_import retention_and_baselines drop_extension kcache_create_extension server_management samples_and_reports kcache_stat_avail export_import retention_and_baselines kcache_drop_extension
(using postmaster on Unix socket, default port)
============== dropping database "contrib_regression" ==============
psql: FATAL:  role "root" does not exist
command failed: "/usr/pgsql-10/bin/psql" -X -c "DROP DATABASE IF EXISTS \"contrib_regression\"" "postgres"
make: *** [installcheck] Error 2
[root@postgres pg_profile]# 

[root@postgres pg_profile]# make USE_PGXS=y sqlfile
make: Nothing to be done for `sqlfile'.
[root@postgres pg_profile]#

**Comment by zubkov-andrei** [comment]
Hi,

1. If you are installing pg_profile in database cluster you want to monitor there is no need in calling create_server function. It is needed only for monitoring other clusters from your current cluster (for example, standby from primary)
2. If you did not any modifications in the extension code, you can easily avoid building an extension from source using make command.. 
3. installcheck fails because you are running it from root user which can't connect to the database. But you do not need to do this at all.
4. sqlfile target of make is intended to obtain extension .sql file used only for manual installation in restricted environments. I think it is not your case too.

So, what you need to do...

1. Obtain latest release from [Releases page](https://github.com/zubkov-andrei/pg_profile/releases). You need only `pg_profile--0.3.3.tar.gz` file
2. Follow the guide provided on release page for installing extension files, i.e. extract obtained package in appropriate folder of your postgres installation and create the extension. You might have dblink extension installed in your database otherwise, pg_profile will not be installed
3. Try to collect the first sample using `select take_sample()`.
4. If you get any error, correct it. The most often is permissions issue. It is recommended to use OS authentication (peer method in pg_hba.conf)
5. If you have got a sample successfully, you might setup periodical samples collection using a cron-like tool.

All the above is described in [Install](https://github.com/zubkov-andrei/pg_profile/blob/0.3.3/doc/pg_profile.md#installation)  and [Taking samples](https://github.com/zubkov-andrei/pg_profile/blob/0.3.3/doc/pg_profile.md#taking-samples) sections the documentation.

**Comment by anandkatti** [comment]
Hi Sir ,

I tried to do that. But none of the samples are getting generated.   Which table to i need to verify that snapshots are gettting generated.

**Comment by anandkatti** [comment]
Waiting for your response. It is urgent.

**Comment by anandkatti** [comment]
is it possible to have zoom or skype call  to fix the things urgently.  Could you please help with that. Urgently. 

I tried all the  options avaliable. But no help.

**Comment by zubkov-andrei** [comment]
Yes it is possible, [zoom](https://us02web.zoom.us/j/84117850837?pwd=VVg2aTE2ZmYxS01qMTBlTm5PRFlPQT09)

**Comment by zubkov-andrei** [comment]
> I tried to do that. But none of the samples are getting generated. Which table to i need to verify that snapshots are gettting generated.

If the `take_sample()` function returns a "OK" message you have a sample.
You can view collected samples using the function `show_samples()`

**Comment by anandkatti** [comment]
postgres=# \dx
                                       List of installed extensions
        Name        | Version |   Schema   |                         Description                          
--------------------+---------+------------+--------------------------------------------------------------
 dblink             | 1.2     | public     | connect to other PostgreSQL databases from within a database
 pg_profile         | 0.1.1   | public     | PostgreSQL load profile repository and report builder
 pg_stat_statements | 1.6     | public     | track execution statistics of all SQL statements executed
 plpgsql            | 1.0     | pg_catalog | PL/pgSQL procedural language
(4 rows)

postgres=#

**Comment by zubkov-andrei** [comment]
> pg_profile | 0.1.1 | public | PostgreSQL load profile repository and report builder
0.1.1 is a obsolete version. Current version is 0.3.3. I think you need to install the latest version.

**Comment by anandkatti** [comment]
postgres=# \dx
                                       List of installed extensions
        Name        | Version |   Schema   |                         Description                          
--------------------+---------+------------+--------------------------------------------------------------
 dblink             | 1.2     | public     | connect to other PostgreSQL databases from within a database
 pg_profile         | 0.1.1   | public     | PostgreSQL load profile repository and report builder
 pg_stat_statements | 1.6     | public     | track execution statistics of all SQL statements executed
 plpgsql            | 1.0     | pg_catalog | PL/pgSQL procedural language
(4 rows)

postgres=# select show_samples();
ERROR:  function show_samples() does not exist
LINE 1: select show_samples();
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
postgres=# select show_sample();
ERROR:  function show_sample() does not exist
LINE 1: select show_sample();
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
postgres=#

**Comment by anandkatti** [comment]
i installed sir .. no error came

**Comment by anandkatti** [comment]
is it possible to have zoom call or skype 
so that i can share my screen ?

**Comment by anandkatti** [comment]
can u gudie me..it is really urgent. Please please ..i really need this extension badly.

**Comment by zubkov-andrei** [comment]
Yes, I've provided you a link and I'm waiting for you there.

> Yes it is possible, [zoom](https://us02web.zoom.us/j/84117850837?pwd=VVg2aTE2ZmYxS01qMTBlTm5PRFlPQT09)
