### ISSUE TITLE
Question about pg_profile

### ISSUE THREAD

**Issue by gael-efluid** [zubkov-andrei/pg_profile#33]
Hello,
First of all, thanks a lot for your work on this wonderful and useful extension !
I've a question about it : I'm currently using multiple dababase on one single instance, so when I generate a report, I see the activity of all databases.
I'd like to know if it is possible to generate a eport on a specific database of an instance that is hosting several databases ?

Kind regards,
Gaël

**Comment by zubkov-andrei** [comment]
Hi!
This is a quite popular question. Unfortunately such report is unavailable and it seems, it won't appear in a future. There is a reason for that - the postgres cluster have some important shared resources reported in *Cluster statistics* and *WAL statistics* sections. Their data is collected  for report interval clusterwide. If a report will contain data for only a limited set of databases, what should we do with the clusterwide stats? We can't include them in a report because they contains workload of other databases and can cause a confusion, but without them the report will be much less informative.
Furthermore *pg_profile* collects only top-objects stats (in a cluster) in a samples, i.e. for some lite databases there may be no data at all. This can also be confusing when the report is built on such lite database.

**Comment by gael-efluid** [comment]
Thanks for the quick answer !
